export const DOM = {
    singInLogin: document.querySelector('#singup-form input[data="login"]'),
    singInPassword: document.querySelector('#signin-form input[data="password"]'),
    singInButton: document.querySelector('#signin-form button'),
    singUpFirstName: document.querySelector('#singup-form input[data="first-name"]'),
    singUpLastName: document.querySelector('#singup-form input[data="last-name"]'),
    singUpLogin: document.querySelector('#singup-form input[data="login"]'),
    singUpPassword: document.querySelector('#singup-form input[data="password"]'),
    singUpButton: document.querySelector('#singup-form button'),
    loginForm: document.querySelector('.container-login'),
    singInInputs: document.querySelectorAll('.inputs-signin'),
    singUpInputs: document.querySelectorAll('.inputs-signup'),
    errorsMessagesSingUp: document.querySelectorAll('.error-signup'),
    errorsMessagesSingIn: document.querySelectorAll('.error-signin'),
    filmsArea: document.querySelector('.films-area'),
    modalIcon: document.querySelector('.modal-icon'),
    mainArea: document.querySelector('.main-area'),
    templateCard: document.querySelector('#template-card').innerHTML,
    loginImg: document.querySelector('.login__img')
}